name: Deploy

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: halexo-vps
    steps:
      - uses: actions/checkout@v4

      - name: Build and deploy
        run: |
          docker compose -f docker-compose.yml up -d --build
          docker image prune -f
